"""First migration

Revision ID: 4c1f3b5e38c6
Revises: 
Create Date: 2022-08-01 02:36:33.107952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c1f3b5e38c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('token', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pkurls')),
    sa.UniqueConstraint('token', name=op.f('uqurlstoken'))
    )
    op.create_index('idx_token', 'urls', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
